language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  app: powerful-ocean-66036
  api_key:
    secure: jopKOvyaWk5UhLIisdyNPoBvul6JKUHUiLTxUCU4nzutQ4dxQCfn3htDjMb1O6LXVhhgWTcyfNoNQNO+wXKITAXeF8C4g4ghMewikxF7JoLe9b7xN3Cm5xkHe4yGZc3hU+WVQ80OoTAf5OGmonUWa0xY73hOqgp0FsH3YnrwldPINRWQCq8A3GCmBysbaASh4D1OiV7L5i2yCv8oCbK6gwdP/RLzwSUhYJO/EjfbQwdpBUbjbjyqjh4JyWtfAXO4zbiXJXIzsF1NTckpINrRQzi8tn063pna/YlBqxBeIhoB3/RfTY5kNVSmbeHZM0nY421gjXV2r5zPcQU1NqvWcacP1a603DThTPg0vBJuQQzYYojKYQboAmEfYbnkF1sIB3jUR+kSLBmBqnicdHxmcPjlB5ah8wqIL6RpS9wYPZU9QRbPzjIwtAKGJgUmnpdQ8DWfk6HcnYDqV2/ejbiR2cqN0G35oKTemDaIAuGUQJfXVeuvyKvInRGVQygm/HMtoCqNZIQpZw0rCZWsZLWBlgLmE+ZPpAx79zdxY9QkvJchx3ngd3D3+wKqi6ozdtSGxp7B5xgLw/1w6mA9HlkrZMa52AOxkezPaj5LGEfeWSB8ytSmYVz5FJaj+Gyz5c9svcD+81WwkBmHKiG5jPJlf65+ybbahzeCwdUjKGXyxFE=