language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: ooziMk8TyBRTifTV9G0V9X27FYZtbQTIOl1wcDv7GjMC1gqx+8FGNSFwtzN4HKXdyeEPtCxc0DbvhUB1vHi4Cj9+jbt5LbWPqH1iyaXLRZWsurk0ChFaRauDm4gq0QFYvhOCBYiA7T55xoof9dD/YdjKIdgEDNCv2b3wZnwch7Hl6bfTuvhzVwGet6i30m0yEYKpEiDSfJLN5R5cfX5a/HxU8HM2rqvrA7Neejv97i0+lBjf7QccshPBrZ7j8nPnU/K75iQf2+FOqWWDvPHRszp+0v3NS8mcsWGADYSXe2F/NWXpwAK9P07hqRqjxoIYTEQBivz/FKjRngYZqUMyg8r0beq2WbZwE5k+Zg3Fo2l1bczqkuD3TVmU4QeEbq851sEzlYlAyGcRq8WLF9M+/JCaXCH+kBr4vruwe2H86nycgjyP2nHtxb+3No3DjXwQP5i+zN/JXKgt9n3kahCaIaBPEg0WyJt5qHC1MeTqQw/tk7uDjqN2LX/kZtEpSkGhfG6ETQ4SEtSsoO9BzAPtJTKobmob9UdWMMh1PFkRNBzZBq4LrNMdLzyUBTEjE2otmBDZezm3Zg7YlGnAsm4UDLTxokWh/w1YOCrl53VgL7Rje4qkjnEDDkyyjkHwoNMOxwi1/9s2Ap2ASHvzlPCjudoK8amwjRV4ZvSGungCitI=
cache:
  directories:
  - node_modules
  - client/node_modules
